<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-FEPQ0C3" ignored="0" name="RerunTestcase(failed)" tests="2" failures="2" timestamp="2022-10-05T17:36:10 IST" time="0.057" errors="0">
  <testcase name="test2" time="0.007" classname="com.prac.failedtestcase.TestClass2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.prac.failedtestcase.TestClass2.test2(TestClass2.java:11)
at java.util.ArrayList.forEach(Unknown Source)
at com.runner.TestRunner.main(TestRunner.java:16)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.0" classname="com.prac.failedtestcase.TestClass3">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.prac.failedtestcase.TestClass3.test3(TestClass3.java:11)
at java.util.ArrayList.forEach(Unknown Source)
at com.runner.TestRunner.main(TestRunner.java:16)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite> <!-- RerunTestcase(failed) -->
